version: '3'

services:
  selfoss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - selfoss_data:/var/www/html/data
    restart: unless-stopped
    environment:
      - TZ=UTC

  # Optional MySQL database service
  # Uncomment if you want to use MySQL instead of SQLite
  # db:
  #   image: mysql:8.0
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: selfoss
  #     MYSQL_USER: selfoss
  #     MYSQL_PASSWORD: selfosspassword

volumes:
  selfoss_data:
  # mysql_data: