version: '3'

services:
  selfoss:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - selfoss_data:/var/www/html/data
    restart: unless-stopped
    environment:
      - TZ=UTC

volumes:
  selfoss_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /usr/share/webapps/selfoss/data/sqlite
